#!/bin/bash
# Dockerhub custom build command
# $IMAGE_NAME var is injected into the build so the tag is correct.

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_SHA=$(git rev-parse --short HEAD
GIT_TAG=$(git tag -l | tail -n 1)
DOCKERFILE="./Dockerfile"

sed -i "s/__BUILD_DATE__/$BUILD_DATE" $DOCKERFILE
sed -i "s/__GIT_SHA__/$GIT_SHA" $DOCKERFILE
sed -i "s/__GIT_TAG__/$GIT_TAG" $DOCKERFILE

docker build -t $IMAGE_NAME .

